name: Test Migration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Git config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Clone test repo
        run: git clone https://austenstone@bitbucket.org/austenstone/main-test1.git
          
      - name: Run script
        working-directory: main-test1
        run: ../migrate-submodules.sh -s 's/bitbucket.org/github.com/g' -b 'master'
          
      - name: Results
        working-directory: main-test1
        run: |
          cat .gitmodules && git submodule foreach --recursive '[ -f .gitmodules ] && cat .gitmodules || true'
          ! grep 'bitbucket'
        
